[project]
name = "datascientist-oc"
version = "0.1.0"
description = "Environnement du projet 2, partie Data Scientist"
authors = [
    {name = "VM"}
]
readme = "README.md"
requires-python = "3.13.5"
dependencies = [
    "pandas==2.2.3",
    "numpy==2.1.3",
    "matplotlib==3.10.0",
    "seaborn==0.13.2",
    "scipy==1.15.3",
    "pycountry==24.6.1"
]


[build-system]
requires = ["poetry-core==2.1.3"]
build-backend = "poetry.core.masonry.api"
